[project]
name = "your-project-name"
version = "0.1.0"
dependencies = [
    "fastapi",
    "sqlmodel",
    "psycopg2-binary", # PostgreSQL adapter
    "uvicorn",
    "psycopg>=3.2.3",
    "asyncpg>=0.30.0",
    "greenlet>=3.1.1",
]
